name: CI

on:
  push:
    branches: [ main, testcase ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential portaudio19-dev libasound2-dev ffmpeg qtbase5-dev qttools5-dev-tools libqt5svg5-dev libqt5webkit5-dev libopenblas-dev pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        python -m pytest tests/ -v